### ISSUE TITLE
Viewpoint adaptation crash when adapting intersection type

### ISSUE THREAD

**Issue by AndrewShf** [eisop/checker-framework#433]
* commands (that can be cut-and-pasted into a command shell)
 `javacheck -cp framework/build/classes/java/test -processor viewpointtest.ViewpointTestChecker  checker/tests/all-systems/IntersectionTypes.java`
 * outputs, and
```
error: Error in AnnotatedTypeMirror.fromExpression(ViewpointTestAnnotatedTypeFactory, call(baz)): ViewpointAdapter::combineAnnotationWithType: Unknown decl: @Top Foo & @Top Bar of kind: INTERSECTION
  ; The Checker Framework crashed.  Please report the crash.
  Compilation unit: checker/tests/all-systems/IntersectionTypes.java
  Last visited tree at line 10 column 1:
  public class IntersectionTypes {
  Exception: org.checkerframework.javacutil.BugInCF: ViewpointAdapter::combineAnnotationWithType: Unknown decl: @Top Foo & @Top Bar of kind: INTERSECTION; org.checkerframework.javacutil.BugInCF: ViewpointAdapter::combineAnnotationWithType: Unknown decl: @Top Foo & @Top Bar of kind: INTERSECTION
        at org.checkerframework.framework.type.AbstractViewpointAdapter.combineAnnotationWithType(AbstractViewpointAdapter.java:378)
        at org.checkerframework.framework.type.AbstractViewpointAdapter.combineAnnotationWithType(AbstractViewpointAdapter.java:282)
        at org.checkerframework.framework.type.AbstractViewpointAdapter.combineTypeWithType(AbstractViewpointAdapter.java:240)
        at org.checkerframework.framework.type.AbstractViewpointAdapter.viewpointAdaptMethod(AbstractViewpointAdapter.java:161)
        at org.checkerframework.framework.type.AnnotatedTypeFactory.methodFromUse(AnnotatedTypeFactory.java:2380)
        at org.checkerframework.framework.type.AnnotatedTypeFactory.methodFromUse(AnnotatedTypeFactory.java:2330)
        at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.methodFromUse(GenericAnnotatedTypeFactory.java:2086)
        at org.checkerframework.framework.type.TypeFromExpressionVisitor.visitMethodInvocation(TypeFromExpressionVisitor.java:381)
        at org.checkerframework.framework.type.TypeFromExpressionVisitor.visitMethodInvocation(TypeFromExpressionVisitor.java:80)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1650)
        at jdk.compiler/com.sun.source.util.SimpleTreeVisitor.visit(SimpleTreeVisitor.java:80)
        at org.checkerframework.framework.type.TypeFromTree.fromExpression(TypeFromTree.java:42)
        at org.checkerframework.framework.type.AnnotatedTypeFactory.fromExpression(AnnotatedTypeFactory.java:1711)
        at org.checkerframework.framework.type.AnnotatedTypeFactory.getAnnotatedType(AnnotatedTypeFactory.java:1353)
        at org.checkerframework.framework.flow.CFAbstractTransfer.getValueFromFactory(CFAbstractTransfer.java:215)
        at org.checkerframework.framework.flow.CFAbstractTransfer.visitMethodInvocation(CFAbstractTransfer.java:1023)
        at org.checkerframework.framework.flow.CFAbstractTransfer.visitMethodInvocation(CFAbstractTransfer.java:97)
        at org.checkerframework.dataflow.cfg.node.MethodInvocationNode.accept(MethodInvocationNode.java:124)
        at org.checkerframework.dataflow.analysis.AbstractAnalysis.callTransferFunction(AbstractAnalysis.java:356)
        at org.checkerframework.dataflow.analysis.ForwardAnalysisImpl.callTransferFunction(ForwardAnalysisImpl.java:391)
        at org.checkerframework.dataflow.analysis.ForwardAnalysisImpl.performAnalysisBlock(ForwardAnalysisImpl.java:157)
        at org.checkerframework.dataflow.analysis.ForwardAnalysisImpl.performAnalysis(ForwardAnalysisImpl.java:110)
        at org.checkerframework.framework.flow.CFAbstractAnalysis.performAnalysis(CFAbstractAnalysis.java:149)
        at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.analyze(GenericAnnotatedTypeFactory.java:1535)
```
 * expectation
 no crash.

**Comment by AndrewShf** [comment]
Intersection type is not considered when doing adaptation.
https://github.com/eisop/checker-framework/blob/master/framework/src/main/java/org/checkerframework/framework/type/AbstractViewpointAdapter.java#L373

**Comment by AndrewShf** [comment]
Related errors of viewpointChecker:
`javacheck -cp framework/build/classes/java/test -processor viewpointtest.ViewpointTestChecker  checker/tests/all-systems/Issue1003.java` : StackOverflow error

`javacheck -cp framework/build/classes/java/test -processor viewpointtest.ViewpointTestChecker  checker/tests/all-systems/Crash.java`: error: AsSuperVisitor: type is not an erased subtype of supertype.
