### ISSUE TITLE
Unknown position for type annotation

### ISSUE THREAD

**Issue by wmdietl** [eisop/checker-framework#47]
From https://github.com/typetools/checker-framework/issues/3277

Compiling the example:

```java
import org.checkerframework.checker.tainting.qual.*;

public class C {
    public static void f() {
        Object o = new @Tainted Generic<?>[0];
    }
}

class Generic<T> {
}
```

with a plain Java 14 javac results in output:

```
ClassWriter: Position UNKNOWN in type annotation: @org.checkerframework.checker.tainting.qual.Tainted
ClassWriter: Position UNKNOWN in type annotation: @org.checkerframework.checker.tainting.qual.Tainted
```

**Comment by wmdietl** [comment]
Even worse, putting this in a field crashes javac 14:

```java
import org.checkerframework.common.aliasing.qual.MaybeAliased;

class Issue3277 {
    Object o = new Generic<@MaybeAliased ?>[0];

    class Generic<U> {
    }
}
```

```
An exception has occurred in the compiler (14). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program, the following diagnostic, and the parameters passed to the Java compiler in your report. Thank you.
java.lang.AssertionError
        at jdk.compiler/com.sun.tools.javac.util.Assert.error(Assert.java:155)
        at jdk.compiler/com.sun.tools.javac.util.Assert.check(Assert.java:46)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.getAndRemoveNonFieldTAs(Gen.java:503)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.normalizeDefs(Gen.java:442)
        at jdk.compiler/com.sun.tools.javac.jvm.Gen.genClass(Gen.java:2388)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.genCode(JavaCompiler.java:756)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.generate(JavaCompiler.java:1646)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.generate(JavaCompiler.java:1614)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:972)
        at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:316)
        at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:176)
        at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:57)
        at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:43)
```
